BEGIN;

DROP TABLE IF EXISTS "Videos", "Tags", "M2M_TagsVideos"; 

CREATE TABLE "Videos" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "name" VARCHAR(255) NOT NULL,
    "description" TEXT, 
    "url" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ
); 

CREATE TABLE "Tags" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "value" TEXT NOT NULL UNIQUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "M2M_TagsVideos" (
    "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "tag_id" INT REFERENCES "Tags"(id) NOT NULL, 
    "video_id" INT REFERENCES "Videos"(id) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO "Videos"("name", "description", "url") VALUES 
('Meow', 'lorem ipsum', 'https://www.youtube.com/shorts/NsMKvVdEPkw'),
('Rouaor', 'lorem ipsum', 'https://www.youtube.com/shorts/NsMKvVdEPkw');

INSERT INTO "Tags"("value") VALUES ('cat'), ('lion'), ('fish');

INSERT INTO "M2M_TagsVideos"("tag_id", "video_id") VALUES (2, 1);

COMMIT;
